main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('plants/', views.plants_index, name='index'),
    path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
    path('plants/<int:pk>/update', views.PlantUpdate.as_view(), name='plants_update'),
    path('plants/<int:pk>/delete', views.PlantDelete.as_view(), name='plants_delete'),
    path('plants/<int:plant_id>/add_watering', views.add_watering, name='add_watering'),
    path('fertilizers/', views.FertilizerList.as_view(), name='fertilizers_list'),
    path('fertilizers/<int:pk>/', views.FertilizerDetail.as_view(), name='fertilizer_detail'),
    path('fertilizers/create/', views.FertilizerCreate.as_view(), name='fertilizers_create'),
    path('fertilizers/<int:pk>/update/', views.FertilizerUpdate.as_view(), name='fertilizers_update'),
    path('fertilizers/<int:pk>/delete/', views.FertilizerDelete.as_view(), name='fertilizers_delete'),
    path('plants/<int:plant_id>/assoc_fertilizer/<int:fertilizer_id>', views.assoc_fertilizer, name='assoc_fertilizer'),
    path('plants/<int:plant_id>/remove_fertilizer/<int:fertilizer_id>/', views.remove_fertilizer, name='remove_fertilizer'),
    path('plants/<int:plant_id>/add_photo', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

plant_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Fertilizer(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.brand} {self.name}"
    
    def get_absolute_url(self):
        return reverse('fertilizer_detail', kwargs={'pk': self.id})

class Plant(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    genus = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    fertilizers = models.ManyToManyField(Fertilizer)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})

class Watering(models.Model):
    date = models.DateField('Watering date')
    fertilized = models.BooleanField('Fertilized?')
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        if self.fertilized == True:
            return f"Fertilized and watered on {self.date}"
        else:
            return f"Watered on {self.date}"
    class Meta:
        ordering = ('-date',)

class Photo(models.Model):
    url = models.CharField(max_length=200)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for plant_id: {self.plant_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm

from .models import Watering

class WateringForm(ModelForm):
    class Meta:
        model = Watering
        fields = ('date', 'fertilized')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import WateringForm
from .models import Plant, Fertilizer, Photo
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'plantcollector-bucket-92'

# Create your views here.

@login_required
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def plants_index(request):
    plants = Plant.objects.filter(user = request.user)
    return render(request, 'plants/index.html', {'plants': plants})

@login_required
def plants_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    watering_form = WateringForm()
    fertilizers_not_used = Fertilizer.objects.exclude(id__in = plant.fertilizers.all().values_list('id'))
    return render(request, 'plants/detail.html', {
        'plant': plant, 
        'watering_form': watering_form,
        'fertilizers': fertilizers_not_used,
    })

@login_required
def add_watering(request, plant_id):
    form = WateringForm(request.POST)
    if form.is_valid():
        new_watering = form.save(commit=False)
        new_watering.plant_id = plant_id
        new_watering.save()
    return redirect('detail', plant_id=plant_id)

@login_required
def assoc_fertilizer(request, plant_id, fertilizer_id):
    Plant.objects.get(id=plant_id).fertilizers.add(fertilizer_id)
    return redirect('detail', plant_id=plant_id)

@login_required
def remove_fertilizer(request, plant_id, fertilizer_id):
    Plant.objects.get(id=plant_id).fertilizers.remove(fertilizer_id)
    return redirect('detail', plant_id=plant_id)

@login_required
def add_photo(request, plant_id):
    photo_file = request.FILES.get('photo-file')
    if photo_file:
        session = boto3.Session(profile_name='plant_collector')
        plant_collector_s3_client = session.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            plant_collector_s3_client.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, plant_id=plant_id)
            photo.save()
        except Exception as error:
            print('****************************')
            print('An error occurred while uploading to S3')
            print(error)
            print('****************************')
    return redirect('detail', plant_id=plant_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'invalid sign up - please try again'
    form = UserCreationForm()
    context = { 'form': form, 'error': error_message}
    return render(request, 'registration/signup.html', context)
    
class PlantCreate(LoginRequiredMixin, CreateView):
    model = Plant
    fields = ('name', 'type', 'genus', 'description')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = Plant
    fields = ('name', 'type', 'genus', 'description')

class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/plants/'

class FertilizerList(LoginRequiredMixin, ListView):
    model = Fertilizer

class FertilizerDetail(LoginRequiredMixin, DetailView):
    model = Fertilizer

class FertilizerCreate(LoginRequiredMixin, CreateView):
    model = Fertilizer
    fields = '__all__'

class FertilizerUpdate(LoginRequiredMixin, UpdateView):
    model = Fertilizer
    fields = ('name', 'brand')

class FertilizerDelete(LoginRequiredMixin, DeleteView):
    model = Fertilizer
    success_url = '/fertilizers/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Plant Collector</h1>
<hr />
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Plant Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script defer src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="light-green darken-1">
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo"
                >&nbsp;&nbsp;PlantCollector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'fertilizers_list' %}">View All Fertilizers</a>
            </li>
            <li><a href="{% url 'fertilizers_create' %}">Add Fertilizer</a></li>
            <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
            <li><a href="{% url 'index' %}">View All My Plants</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Log In</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer light-green darken-1">
      <div class="center">
        All Rights Reserved, &copy; 2022 Plant Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/fertilizer_confirm_delete.html
{% extends 'base.html' %} {% block content%}

<h1>Are you sure you want to remove {{ object.name }}?</h1>

<form action="" method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Yes - Remove" class="btn red" />
  <a href="{% url 'fertilizer_detail' object.id %}" class="btn blue">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/fertilizer_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Fertilizer Detail</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ object.name }}</span>
    <p>Brand: {{ object.brand }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'fertilizers_update' object.id %}">Edit</a>
    <a href="{% url 'fertilizers_delete' object.id %}">Delete</a>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/fertilizer_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit {{ object.name}}'s info</h1>
{% else%}
<h1>Add a new fertilizer</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>

  <input
    class="btn blue"
    type="submit"
    value="{% if object %} Edit {% else %} Add {% endif %}"
  />
  {% if object %}
  <a class="btn red" href="{% url 'fertilizer_detail' object.id %}">Cancel</a>
  {% else %}
  <a class="btn red" href="{% url 'home' %}">Cancel</a>
  {% endif %}
</form>

{% endblock %}

main_app/templates/main_app/fertilizer_list.html
{% extends 'base.html' %} {% block content %}

<h1>Fertilizer List</h1>

{% for fertilizer in object_list %}
<div class="card">
  <a href="{% url 'fertilizer_detail' fertilizer.id %}">
    <div class="card-content">
      <span class="card-title">{{ fertilizer.name }}</span>
      <p>Brand: {{ fertilizer.brand }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %} {% block content%}

<h1>Are you sure you want to remove {{ object.name }}</h1>

<form action="" method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Yes - Remove" class="btn red" />
  <a href="{% url 'detail' object.id %}" class="btn blue">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit {{ object.name}}'s info</h1>
{% else%}
<h1>Add a new Plant</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>

  <input
    class="btn blue"
    type="submit"
    value="{% if object %} Edit {% else %} Add {% endif %}"
  />
  {% if object %}
  <a class="btn red" href="{% url 'detail' object.id %}">Cancel</a>
  {% else %}
  <a class="btn red" href="{% url 'home' %}">Cancel</a>
  {% endif %}
</form>

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Plant Detail</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ plant.name }}</span>
                <p>Type: {{ plant.type }}</p>
                <p>Genus: {{ plant.genus }}</p>
                <p>Description: {{ plant.description }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'plants_update' plant.id %}">Edit</a>
                <a href="{% url 'plants_delete' plant.id %}">Delete</a>
            </div>
        </div>
        {% for photo in plant.photo_set.all %}
        <img src="{{ photo.url }}" alt="{{ plant.name }}" class="responsive-img card-panel">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form 
            action="{% url 'add_photo' plant.id %}" 
            class="card-panel" 
            method="POST" 
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            <input type="file" name="photo-file">
            <input type="submit" value="Upload Photo" class="btn green">
        </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_watering' plant.id %}" method="POST">
            {% csrf_token %} {{ watering_form.non_field_errors }}
            <div class="fieldWrapper">
                {{ watering_form.date.errors }}
                <label for="{{ watering_form.date.id_for_label }}"
                    >Watering date:</label
                >
                {{ watering_form.date }}
            </div>
            <div class="fieldWrapper">
                {{ watering_form.fertilized.errors }}
                <label for="{{ watering_form.fertilized.id_for_label }}">
                    {{ watering_form.fertilized }}
                    <span>{{ watering_form.fertilized.label }}</span>
                </label>
            </div>
            <input type="submit" value="Add Watering" class="btn blue" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Fertilized?</th>
                </tr>
            </thead>
            <tbody>
                {% for watering in plant.watering_set.all %}
                <tr>
                    <td>{{ watering.date }}</td>
                    <td>{{ watering.fertilized }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
        <h3>Fertilizers for {{ plant.name }}</h3>
        {% if plant.fertilizers.count %} 
            {% for fertilizer in plant.fertilizers.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ fertilizer.brand }} {{ fertilizer.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'remove_fertilizer' plant.id fertilizer.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn red">Remove</button>
                        </form>
                    </div>
                </div>
            {% endfor %} 
        {% else %}
            <h6>{{ plant.name }} has no fertilizers at this time</h6>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Fertilizers</h3>
        {% if fertilizers.count %} {% for fertilizer in fertilizers %}
        <div class="card">
            <div class="card_content">
                {{ fertilizer.brand }} {{ fertilizer.name }}
            </div>
            <div class="card-action">
                <form
                    action="{% url 'assoc_fertilizer' plant.id fertilizer.id %}"
                    method="POST"
                >
                    {% csrf_token %}
                    <button type="submit" class="btn green">Add</button>
                </form>
            </div>
        </div>
        {% endfor %} {% else %}
        <h6>
            {{ plant.name }} is already being fertilized with all available
            fertilizers. Please be advised that if this number is more than at
            most 2, that is definitely overkill.
        </h6>
        {% endif %}
    </div>
</div>
{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %} {% block content %}

<h1>Plant List</h1>

{% for plant in plants %}
<div class="card">
  <a href="{% url 'detail' plant.id %}">
    <div class="card-content">
      <span class="card-title">{{ plant.name }}</span>
      <p>Type: {{ plant.type }}</p>
      <p>Genus: {{ plant.genus }}</p>
      <p>Description: {{ plant.description }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}